[package]
name = "codecrafters-sqlite"
version = "0.1.0"
authors = ["Linda Siemons <linda@catbrained.dev>"]
edition = "2021"
rust-version = "1.81"

[dependencies]
anyhow = "1.0.89"                                # error handling
